apiVersion: v1
kind: Service
metadata:
  name: cicd-app
  namespace: default
spec:
  selector:
    app: cicd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Change if you use ClusterIP or NodePort
