apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/abayomi2/cicd-jenkins-AgroCD.git'
    targetRevision: HEAD
    path: argocd/manifests
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
