name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t abayomi2/gitops-app:latest ./app
          docker push abayomi2/gitops-app:latest

      - name: Update deployment manifest
        run: |
          sed -i 's|abayomi2/gitops-app:.*|abayomi2/gitops-app:latest|' manifests/deployment.yaml
          git config user.name "GitOps Bot"
          git config user.email "bot@example.com"
          git add manifests/deployment.yaml
          git commit -m "Update image tag"
          git push
